CREATE SEQUENCE [MASTER_COOKS].[seq_empleado_legajo]
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE [MASTER_COOKS].[seq_pago_numero]
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE [MASTER_COOKS].[seq_envio_codigo]
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE [MASTER_COOKS].[seq_deta_codigo]
START WITH 1
INCREMENT BY 1;