@startuml

entity BI_Dim_Tiempo <<Dimension>> {
    **PK | tiempo_id: varchar(20)**
    --
    tiempo_anio: char(4)
    tiempo_mes: char(2)
    tiempo_cuatrimestre: char(1)
}

entity BI_Dim_Ubicacion <<Dimension>> {
    **PK | ubicacion_id: varchar(110)**
    --
    ubicacion_provincia: varchar(60)
    ubicacion_localidad: varchar(50)
}

entity BI_Dim_Sucursal <<Dimension>> {
    **PK | sucursal_id: decimal(6,0)**
    --
    FK | sucursal_ubicacion: varchar(110)
}

entity BI_Dim_Rango_Etario <<Dimension>> {
    **PK | rango_id: decimal(2,0)**
    --
    rango_descripcion: varchar(50)
}

entity BI_Dim_Cliente <<Dimension>> {
    **PK | cliente_id: varchar(50)**
    --
    FK | cliente_ubicacion: varchar(110)
    FK | cliente_rango_etario: decimal(2,0)
}

entity BI_Dim_Empleado <<Dimension>> {
    **PK | empleado_id: varchar(60)**
    --
    FK | empleado_rango_etario: decimal(2,0)
    FK | empleado_sucursal: decimal(6,0)
}

entity BI_Dim_Turno <<Dimension>> {
    **PK | turno_id: decimal(6,0)**
    --
    turno_hora_inicio: datetime
    turno_hora_fin: datetime
}

entity BI_Dim_Medio_Pago <<Dimension>> {
    **PK | medio_pago_id: varchar(50)**
    --
    medio_pago_tipo: varchar(30)
}

entity BI_Dim_Categoria <<Dimension>> {
    **PK | categoria_id: varchar(20)**
    --
    categoria_subcategoria: decimal(8,0)
    categoria_nombre: decimal(8,0)
}

entity BI_Dim_Tipo_Caja <<Dimension>> {
    **PK | tipo_caja_id: varchar(50)**
    --
}

entity BI_Fact_Ventas <<Facts>> {
    **PK,FK | tiempo_id: varchar(20)**
    **PK,FK | sucursal_id: decimal(6,0)**
    **PK,FK | cliente_id: varchar(50)**
    **PK,FK | empleado_id: varchar(60)**
    **PK,FK | turno_id: decimal(6,0)**
    **PK,FK | tipo_caja_id: varchar(50)**
    --
    importe_total: decimal(12,2)
    cantidad_ventas: decimal(12,0)
    cantidad_unidades: decimal(12,0)
}

entity BI_Fact_Promociones <<Facts>> {
    **PK,FK | categoria_id: varchar(20)**
    **PK,FK | tiempo_id: varchar(20)**
    --
    monto_descuento_promocion: decimal(18,2)
    ticket_total: decimal(18,2)
    cantidad_tickets: decimal(18,0)
    porcentaje_descuento: decimal(5,2)
}

entity BI_Fact_Pagos <<Facts>> {
    **PK,FK | tiempo_id: varchar(20)**
    **PK,FK | medio_pago_id: varchar(50)**
    **PK,FK | sucursal_id: decimal(6,0)**
    **PK,FK | cliente_id: varchar(50)**
    **PK,FK | rango_id: decimal(2,0)**
    --
    importe_pago_en_cuotas: decimal(12,2)
    importe_pago_total: decimal(12,2)
    descuento_total: decimal(12,2)
}

entity BI_Fact_Envio <<Facts>> {
    **PK,FK | tiempo_id: varchar(20)**
    **PK,FK | sucursal_id: decimal(6,0)**
    **PK,FK | cliente_id: varchar(50)**
    **PK,FK | rango_id: decimal(2,0)**
    --
    costo_envio_total: decimal(12,2)
    cantidad_envios: int
    envios_cumplidos: int
}

BI_Dim_Tiempo ||---|{ BI_Fact_Ventas
BI_Dim_Sucursal ||---|{ BI_Fact_Ventas
BI_Dim_Cliente ||---|{ BI_Fact_Ventas
BI_Dim_Empleado ||---|{ BI_Fact_Ventas
BI_Dim_Turno ||---|{ BI_Fact_Ventas
BI_Dim_Tipo_Caja ||---|{ BI_Fact_Ventas

BI_Dim_Tiempo ||---|{ BI_Fact_Promociones
BI_Dim_Categoria ||---|{ BI_Fact_Promociones

BI_Dim_Tiempo ||---|{ BI_Fact_Pagos
BI_Dim_Medio_Pago ||---|{ BI_Fact_Pagos
BI_Dim_Sucursal ||---|{ BI_Fact_Pagos
BI_Dim_Cliente ||---|{ BI_Fact_Pagos
BI_Dim_Rango_Etario ||---|{ BI_Fact_Pagos

BI_Dim_Tiempo ||---|{ BI_Fact_Envio
BI_Dim_Sucursal ||---|{ BI_Fact_Envio
BI_Dim_Cliente ||---|{ BI_Fact_Envio
BI_Dim_Rango_Etario ||---|{ BI_Fact_Envio

BI_Dim_Sucursal ||---|{ BI_Dim_Ubicacion
BI_Dim_Cliente ||----|{ BI_Dim_Ubicacion
BI_Dim_Empleado ||---|{ BI_Dim_Sucursal
BI_Dim_Empleado ||--|{ BI_Dim_Rango_Etario
BI_Dim_Cliente ||---|{ BI_Dim_Rango_Etario

@enduml
